title: Second Brain
description: Personal knowledge management system using PARA method
baseurl: "/second-brain"
url: "https://dsamuelhodge.github.io"

# Theme settings
theme: just-the-docs
color_scheme: dark

# Enable search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/DSamuelHodge/second-brain"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Heading anchor links
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025 Second Brain. Distributed under an MIT license."

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  areas:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:collection/:path/
  archives:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
  - scope:
      path: ""
      type: "areas"
    values:
      layout: page
  - scope:
      path: ""
      type: "resources"
    values:
      layout: page
  - scope:
      path: ""
      type: "archives"
    values:
      layout: page

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

# Just the Docs settings
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false