remote_theme: just-the-docs/just-the-docs

title: Second Brain
description: Personal knowledge management system using PARA method
baseurl: "/second-brain"
url: "https://dsamuelhodge.github.io"

# Theme settings
search_enabled: true
heading_anchors: true
color_scheme: dark

# Syntax highlighting settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  areas:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
  - scope:
      path: ""
      type: areas
    values:
      layout: page
  - scope:
      path: ""
      type: resources
    values:
      layout: page

# Additional settings
aux_links:
  "GitHub Repository": 
    - "https://github.com/DSamuelHodge/second-brain"

# Enable copy buttons on code blocks
enable_copy_code_button: true

# Footer content
footer_content: "A personal knowledge management system using PARA method."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"