title: Second Brain
description: Personal knowledge management system using PARA method
baseurl: "/second-brain"
url: "https://dsamuelhodge.github.io"

remote_theme: just-the-docs/just-the-docs
color_scheme: tokyo-night

# Enable search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_external_links:
  - title: "GitHub"
    url: "https://github.com/DSamuelHodge/second-brain"
    hide_icon: false

# Collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Just the Docs configurations
heading_anchors: true
footer_content: "Made with Just the Docs Jekyll theme"
back_to_top: true
back_to_top_text: "Back to top"

# Enable copy buttons on code blocks
enable_copy_code_button: true

# Default YAML frontmatter settings
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: "default"
      nav_exclude: false
      search_exclude: false

# Exclude from processing
exclude:
  - "*.gem"
  - "*.gemspec"
  - "Gemfile*"
  - "node_modules"
  - "package*.json"
  - "vendor"

# kramdown settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1